language: python

python:
  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"

script:
  - py.test tests/test_pcp.py

before_script:
  - pip install --upgrade pip
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
