language: python

python:
  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"

script:
  - py.test tests/test_pcp.py

before_script:
  - pwd > ~/virtualenv/python3.5/site-packages/chordal.pth
  - pwd > ~/virtualenv/python3.4/site-packages/chordal.pth
